version: '3'

services:
  frontend:
    image: eeacms/volto-starter-kit
    ports:
    - "8000:8000"
    - "8001:8001"
    depends_on:
    - ploneapi
    environment:
      API_PATH: "http://localhost:8080/Plone"
      INTERNAL_API_PATH: "http://ploneapi:8080/Plone"
      PORT: "8000"

  ploneapi:
    image: eeacms/plonesaas-devel
    ports:
      - "8080:8080"
    environment:
      CORS_ALLOW_ORIGIN: "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000"
    depends_on:
    - memcached
    volumes:
    - data:/data

  memcached:
    image: memcached
    command:
    - "-m"
    - "512"

volumes:
  data:
    driver: local
